/* Copyright 2026 上海如静知华信息科技有限公司 */
export const domain={
 code:'SUPPLYAI',systemName:'知华供应链风险 AI 平台',englishName:'SUPPLY CHAIN RISK AI',theme:{primary:'#79523c',dark:'#3f352e',accent:'#c99a52'},
 workspace:'集团供应链中心 / 风险控制组',fieldWorkspace:'华东采购中心 / 供应保障组',period:'2026-08-15 · 本周态势',liveText:'供应风险于 10:42 更新',fieldContextLabel:'保障周期',fieldContext:'未来 14 天',fieldUser:'江宁',fieldRole:'供应保障专员',adminUser:'沈川',adminRole:'供应链风控负责人',
 adminTitle:'供应链风险战情中心',adminBreadcrumb:'供应智能 / 风险态势',adminSubtitle:'连接供应商、采购订单、物流与库存数据，识别断供、延期和集中度风险并形成可解释的处置建议。',exportAction:'导出风险报告',createAction:'新建评估任务',
 chartTitle:'重点物料供应稳定度',chartSubtitle:'实际稳定度 / 管控目标',chartLabels:['05日','06日','07日','08日','09日','10日','11日','12日','13日'],loadTitle:'供应风险分布',loadSubtitle:'不同风险等级占当前纳管供应商比例',recordsTitle:'重点供应风险任务',recordsSubtitle:'按断供概率、影响范围和交付窗口排序',issueTitle:'需要处理的供应异常',issueSubtitle:'来自供应商、采购订单和物流节点',
 recordName:'风险任务',itemName:'供应对象',unitName:'责任团队',batchName:'评估依据',planName:'核查项',doneName:'已确认',exceptionName:'异常',unitLabel:'项',
 listBreadcrumb:'供应风险 / 评估任务',listSubtitle:'将供应商能力、订单履约、物流在途和库存缓冲汇总为可解释的处置优先级。',listSummary:[['纳管供应商','286'],['本周评估','74'],['高风险','8',true],['已闭环','39']],tabs:['全部','待评估','处置中','待复核','已归档'],
 fieldBreadcrumb:'保障工作台 / 供应专员',fieldTitle:'供应保障工作台',fieldSubtitle:'负责供应商 32 家 · 今日核查 11 项 · 待处理风险 4 条',fieldSecondary:'查看交付日历',reportAction:'提交保障反馈',fieldNoticeTitle:'核心采购数据同步正常',fieldNotice:'订单数据覆盖率 97.8%',
 steps:['数据汇聚','风险评估','影响分析','人工处置','结果复盘'],documentAction:'查看供应档案',printAction:'导出供应保障单',resourceCardTitle:'供应链数据资源',resourceValueLabel:'接入对象',resourceHealthLabel:'数据健康度',quickSubtitle:'常用供应保障入口',
 quickActions:[['风险评估','/shopfloor/report','供应、交付与库存证据'],['供应档案','/shopfloor/material','供应商、物料和订单信息'],['数据资源','/shopfloor/resources','SRM、WMS、TMS 和模型'],['风险升级','/shopfloor/andon','重大断供与集中度风险协同']],
 reportDefaults:[7,2],reportTitle:'供应风险处置反馈',reportSubtitle:'记录交付承诺、替代资源和库存保障安排。',reportSuccess:'供应保障反馈已提交',reportPlaceholder:'填写供应变化、交付承诺、替代方案和处置动作',reportFootnote:'提交后进入供应链风控负责人复核队列',ruleTitle:'供应风险决策门禁',ruleSubtitle:'SUPPLY-AI · V1.0',rules:[['来源数据','订单与库存必须可核验'],['供应切换','授权人员审批'],['风险调整','保留原因证据'],['结果复盘','保障周期结束后执行',true]],fieldTotals:[['32','负责供应商'],['4','待处理风险'],['11','今日核查'],['97.8%','订单覆盖率']],
 adminMenus:[['/admin','home','风险战情中心'],['/admin/work-orders','order','评估任务'],['/admin/samples','box','供应对象'],['/admin/schedule','calendar','交付日历'],['/admin/methods','process','评估规则'],['/admin/reviews','quality','处置复核'],['/admin/resources','machine','数据资源'],['/admin/report','chart','供应分析']],fieldMenus:[['/shopfloor','home','保障工作台'],['/shopfloor/report','report','处置反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','供应档案'],['/shopfloor/resources','machine','数据状态'],['/shopfloor/andon','risk','风险升级',4]],
 moduleTitles:{tasks:['我的评估任务','查看断供概率、影响等级和处置状态'],material:['供应对象档案','查看供应商、物料、订单和替代资源'],resources:['供应链数据中心','管理 SRM、WMS、TMS 和风险模型'],andon:['供应风险升级','提交重大断供和集中度风险'],samples:['供应对象台账','统一管理供应商和关键物料'],schedule:['供应交付日历','协调订单、到货与安全库存窗口'],methods:['风险评估规则','维护权重、阈值和情景参数'],reviews:['供应处置复核','记录确认、驳回和补充信息'],report:['供应韧性分析','分析履约、集中度和替代能力']},
 tagline:'提前识别供应中断，构建更有韧性的供应链',storyTitle:'把分散的供应信号，<br/>变成可执行的保障计划',storyText:'连接采购、库存和物流数据，帮助供应团队提前准备并坚持人工决策。',pattern:[2,5,8,11,14,17,20,23,26,29,32],loginStats:[['286','纳管供应商'],['97.8%','订单覆盖率'],['8','高风险对象']],loginTitle:'供应链风险战情中心',adminDemo:'履约 / 集中度 / 替代',fieldDemo:'评估 / 处置 / 复核'}
export const records=[{no:'SR-260815-018',name:'精密轴承断供风险评估',code:'MAT-BRG-017',unit:'关键物料组',group:'机加物料',plan:12,done:7,exception:3,due:'08-15',batch:'SRM+库存',status:'处置中',progress:58,priority:'高风险'},{no:'SR-260815-021',name:'华东电子料交付稳定性',code:'SUP-HD-083',unit:'电子采购组',group:'电子元件',plan:9,done:6,exception:1,due:'08-16',batch:'订单+物流',status:'待复核',progress:67,priority:'关注'},{no:'SR-260815-026',name:'进口密封件替代资源评估',code:'MAT-SEAL-032',unit:'战略采购组',group:'进口物料',plan:10,done:2,exception:2,due:'08-16',batch:'供应商+替代',status:'待评估',progress:20,priority:'高风险'},{no:'SR-260814-015',name:'华南包装材料履约评估',code:'SUP-HN-026',unit:'间接采购组',group:'包装物料',plan:8,done:8,exception:0,due:'08-14',batch:'订单+质检',status:'已归档',progress:100,priority:'正常'},{no:'SR-260815-031',name:'控制器单一来源风险评估',code:'MAT-PLC-006',unit:'供应风控组',group:'自动化元件',plan:11,done:7,exception:2,due:'08-17',batch:'集中度+库存',status:'处置中',progress:64,priority:'关注'}]
export const resources=[{code:'SRM-01',name:'供应商协同平台',unit:'供应链数字化组',status:'运行中',health:99,value:'286',valueUnit:'家',note:'核心供应商履约数据更新时间小于十分钟'},{code:'MODEL-02',name:'供应中断风险模型',unit:'供应风控组',status:'复核中',health:94,value:'v2.3',valueUnit:'',note:'8 个对象进入高风险队列'},{code:'TMS-03',name:'物流在途数据连接器',unit:'物流管理组',status:'预警',health:89,value:'1,264',valueUnit:'单',note:'12 个在途节点等待状态回补'}]
export const reviews=[{no:'RV-260815-032',title:'精密轴承断供风险复核',type:'替代切换',detail:'涉及 3 个生产基地 · 沈川',result:'待确认'},{no:'RV-260815-011',title:'华东电子料交付承诺确认',type:'风险调整',detail:'6 笔采购订单 · 江宁',result:'通过'},{no:'RV-260814-018',title:'进口密封件保障证据',type:'证据补充',detail:'缺少替代供应商产能证明',result:'异常'}]
export const adminMetrics=[['供应稳定度','91.6%','较上周提升 1.8%','blue'],['高风险对象','8','影响 17 项关键物料','red'],['准时交付率','94.2%','本周 1,264 笔订单','green'],['待批处置','11','涉及替代供应商 6 家','orange']]
export const fieldMetrics=[['我的任务','7','4 项高风险','blue'],['今日已核查','11','全部保留来源证据','green'],['待处理风险','4','2 项存在断供风险','orange'],['订单覆盖率','97.8%','较上周提升 0.6%','slate']]
export const chartActual=[96,95,94,92,90,89,91,92,93],chartTarget=[95,95,95,95,95,95,95,95,95]
export const loads=[['关键原料',86,'高风险 3 项'],['进口物料',73,'高风险 2 项'],['电子元件',58,'高风险 2 项'],['包装物料',34,'高风险 1 项']]
export const issues=[['断供','精密轴承供应商产线临时停产','建议启动华南替代供应商试供','待批准'],['延期','华东电子料两笔订单预计延期','已由采购负责人重新确认交付日期','处理中'],['集中度','控制器单一来源占比超过阈值','建议启动第二来源认证','需协调']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
